//                          GUESS THE NUMBER !
// This is a Game based on C language . In this program the player has to Guess the number 
// generated by the system between a set minimum and maximum limit.

// Instructions to play the game: 
// 1. Please choose one of the options out of the given menu to proceed.
//    choose 1 to PLAY and 2 to EXIT
// 2. Next step is to provide the range
//    please provide the max and min limit 
// 3. Try to Guess the number generated by the program
// 4. System will provide hints to help you guess the number easily.
// 5. Play it with you friends. Whoever guessed the correct number in minimum number of attempts 
//    is the winner !
//                          ...ENJOY... 


#include <stdio.h>
#include <stdlib.h>        // srand(),rand()
#include <time.h>          // time(0)
int main(int argc, char const *argv[])
{
    int choice;
    printf("**************************************************************************\n");
    printf("\t\t\t\t...GAME...\n");
    printf("**************************************************************************\n");
    printf("\t\t            |GUESS THE NUMBER| \n");
    printf("**************************************************************************\n");
    while (1)
    {
        printf("1.Play\n2.Exit\nEnter your choice(1/2) : ");
        scanf("%d", &choice);
        if (choice == 1)
        {
            printf("Let's PLAY !\n");
            printf("**************************************************************************\n");
            int number, guess, min, max, count = 1;
            printf("Enter the minimum limit : ");
            scanf("%d", &min);
            printf("Enter the maximum limit : ");
            scanf("%d", &max);
            srand(time(0));                 // initialising the seed value for rand() function
            number = rand() % (max - min + 1) + min;    // generating a random number between the range
            do
            {
                printf("Enter a number between %d and %d : ", min, max);
                scanf("%d", &guess);
                if (guess < number)
                {
                    printf("Greater number please !\n");
                }
                else if (guess > number)
                {
                    printf("Lower number please !\n");
                }
                else
                {
                    printf("**************************************************************************\n");
                    printf("You guessed it right !\nTotal attempts = %d\n", count);
                }
                count++;
            } while (guess != number);
            printf("**************************************************************************\n");
        }
        else if (choice == 2)
        {
            printf("Well Played.\n");
            break;
        }
    }
    

    return 0;
}
